app_name: powertrack
app_dir: /var/www/powertrack
repo_url: https://github.com/ttsaryanski/electricity-bills-archive-and-analytics
repo_branch: main
node_major: "22"
swap_size_mb: 4096
app_port: 3000
domain_name: powertrack.duckdns.org
admin_email: ttsaryanski@gmail.com

# Blue/green deployment settings
active_color: blue
blue_port: 3001
green_port: 3002
app_base_dir: /var/www/powertrack
app_name_base: powertrack
active_color_file: /etc/powertrack-active-color

# Prometheus
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"
prometheus_retention_time: "15d"
prometheus_app_target: "127.0.0.1:80"
prometheus_listen_address: "0.0.0.0:9090"
prometheus_allowed_ip: "127.0.0.1"
prometheus_data_device: "/dev/disk/azure/scsi1/lun10"
prometheus_storage_path: "/var/lib/prometheus"

# Grafana
grafana_listen_address: "127.0.0.1"
grafana_port: 3003
grafana_data_path: "{{ prometheus_storage_path }}/grafana"
grafana_dashboards_path: "{{ grafana_data_path }}/dashboards"
grafana_prometheus_url: "http://127.0.0.1:9090"
grafana_prometheus_uid: "prometheus"

# Docker-based blue/green deployment
image_repository: ghcr.io/ttsaryanski/electricity-bills-archive-and-analytics
image_tag: latest
docker_env_base_dir: /var/www/powertrack-env