import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./nav/page";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <head>
                <script
                    src="https://kit.fontawesome.com/3b7d954735.js"
                    crossOrigin="anonymous"
                ></script>
            </head>
            <body className="min-h-full flex flex-col">
                <StackProvider app={stackClientApp}>
                    <StackTheme>
                        <NavigationBar />
                        {children}
                    </StackTheme>
                </StackProvider>
            </body>
        </html>
    );
}
