{
 "title": "PowerTrack - Business",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bills added successfully",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(powertrack_bills_created_total[365d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bills deleted successfully",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(powertrack_bills_deleted_total[365d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add bill form validation error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(powertrack_bills_validation_total[365d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Address added successfully",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(powertrack_address_created_total[365d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Address deleted successfully",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(powertrack_address_deleted_total[365d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add address form validation error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(powertrack_address_validation_total[365d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}