{
 "title": "PowerTrack - Infrastructure",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - avg by (instance) (\r\n    rate(node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_memory_MemAvailable_bytes{job=\"node_exporter\"}\r\n    /\r\n    node_memory_MemTotal_bytes{job=\"node_exporter\"}\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load (5 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent disk usage in percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  (\r\n    node_filesystem_avail_bytes{\r\n      job=\"node_exporter\",\r\n      mountpoint=\"/var/lib/prometheus\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n    /\r\n    node_filesystem_size_bytes{\r\n      job=\"node_exporter\",\r\n      mountpoint=\"/var/lib/prometheus\",\r\n      fstype!~\"tmpfs|overlay\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent disk free space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{\r\n  job=\"node_exporter\",\r\n  mountpoint=\"/var/lib/prometheus\",\r\n  fstype!~\"tmpfs|overlay\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nethwork speed - in/out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node_exporter\",device=\"eth0\"}[5m]) * 8 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node_exporter\",device=\"eth0\"}[5m]) * 8 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}